name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1n6o6vXv1K8g0LYKXysHxaky2cI_4M4sd4hJiQpHoS8TiP2xQ
        USER_PASS: 1419628626
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h
